language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements-test.txt
  - pip install .[all]
  - pip install codecov
  
# command to run tests
script:
  - pytest
  - codecov

before_deploy:
  - python setup.py bdist_wheel
  - pip install -U s3pypi
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - make -C docs html

deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    skip_cleanup: true
    name: v$TRAVIS_TAG
    overwrite: true
    file_glob: true
    file: dist/*
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -release$"

  # Prod deployment
  - provider: pypi
    username: "__token__"
    password: $PYPITOKEN
    skip_existing: true
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -release$"

  #Stage deployment
  - provider: script
    script: s3pypi --bucket $AWS_BUCKET --region $AWS_REGION --force --private --no-sdist --dist-path dist --secret deeplite-stage
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -stage$"

  # - provider: pages
  #   skip_cleanup: true
  #   github_token: $GITHUB_TOKEN
  #   local_dir: docs/_build/html
  #   on:
  #     branch: master
  #     tags: true
  #     condition: "$TRAVIS_TAG =~ -release$"
