language: python
jobs:
  include:
    # perform a linux build
    - services: docker
      python: 3.6
      env: CIBW_BUILD="cp36-manylinux_x86_64"

    - services: docker
      python: 3.7
      env: CIBW_BUILD="cp37-manylinux_x86_64"

    - services: docker
      python: 3.8
      env: CIBW_BUILD="cp38-manylinux_x86_64"

# command to install dependencies
before_install:
  - python3 -m pip install --upgrade pip

# command to install dependencies
install:
  - python3 -m pip install -r requirements-test.txt
  - pip install .[all]
  - python3 -m pip install codecov
  
# command to run tests
script:
  - pytest
  - codecov

before_deploy:
  - python3 -m pip install -U s3pypi
  - python3 -m pip install twine
  - python3 -m pip install cibuildwheel==1.10.0
  - python3 -m cibuildwheel --archs x86_64 --output-dir  wheelhouse
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - make -C docs html

deploy:
  # Prod deployment
  - provider: releases
    token: $GITHUB_TOKEN
    skip_cleanup: true
    name: v$TRAVIS_TAG
    overwrite: true
    file_glob: true
    file: wheelhouse/*
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -release$"

  # Prod deployment
  - provider: script # PyPi
    script: python3 -m twine upload --skip-existing wheelhouse/*.whl
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -release$"

  #Stage deployment
  - provider: script
    script: s3pypi --bucket $AWS_BUCKET --region $AWS_REGION --force --private --no-sdist --dist-path wheelhouse --secret deeplite-stage
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -stage$"

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ -release$"

env:
  global:
    - CIBW_BUILD_VERBOSITY=1
    - CIBW_BEFORE_BUILD="pip install -U Cython && python setup.py build_ext --inplace"
    - TWINE_USERNAME="__token__"
    - TWINE_PASSWORD=$PYPITOKEN
